version: "2"

services:
  bridge:
    image: v1ll4n/yak-bridge:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    network_mode: host
    restart: always
    command: yak bridge --dnslog --domain dnstunnel.run
