version: "3"

services:
  bridge:
    image: v1ll4n/yak-bridge:latest
    network_mode: host
    deploy:
      restart_policy:
        condition: always
    command: yak bridge --secret your-secret-for-yak-BRIDG3

